version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/finance-dashboard-go:latest
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    restart: unless-stopped 