name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  #    - name: Set up Node.js
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: '18'
  #        cache: 'npm'

  #    - name: Install frontend dependencies
  #      run: |
  #        cd frontend-react
  #        npm install

  #    - name: Run frontend tests
  #      run: |
  #        cd frontend-react
  #        npm test

  #    - name: Set up Python
   #     uses: actions/setup-python@v3
    #    with:
     #     python-version: '3.9'
      #    cache: 'pip'

    #  - name: Install Python dependencies
    #    run: |
    #      cd backend-python
    #      pip install -r requirements.txt

    #  - name: Run Python tests
    #    run: |
    #      cd backend-python
    #      pytest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Run Go tests
        run: |
          cd backend-go
          go test ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  #    - name: Build and push frontend
  #      uses: docker/build-push-action@v4
  #      with:
  #        context: ./frontend-react
  #        push: true
  #        tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-frontend:latest

  #    - name: Build and push Python backend
  #      uses: docker/build-push-action@v4
  #      with:
  #        context: ./backend-python
  #        push: true
  #        tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-python:latest

      - name: Build and push Go backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend-go
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-go:latest

  #deploy-staging:
  #  name: Deploy to Staging
  #  needs: build
  #  if: github.ref == 'refs/heads/develop'
  #  runs-on: ubuntu-latest
  #  environment: staging
  #  steps:
  #    - name: Deploy to staging
  #      run: echo "Deploying to staging environment"
  #      # Add your staging deployment commands here

  deploy-production:
    name: Deploy Go Backend to Production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Go backend to production
        run: |
          echo "Deploying Go backend to production environment"
          # Add your Go backend production deployment commands here
