name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: true

      - name: Run Go tests
        run: |
          cd backend-go
          go test ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Go backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend-go
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-go:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-go:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/finance-dashboard-go:buildcache,mode=max

  deploy-production:
    name: Deploy Go Backend to Production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Go backend to production
        run: |
          echo "Deploying Go backend to production environment"
          # Add your Go backend production deployment commands here
