name: CI/CD Pipeline

on:
  push:
    branches: [ main, EthanTest ]
  pull_request:
    branches: [ main, EthanTest ]

env:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: true

      - name: Run Go tests
        run: |
          cd backend-go
          go test ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Go backend
        run: |
          cd backend-go
          which docker
          which docker-compose
          docker compose version
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy-production:
    name: Deploy Go Backend to Production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy Go backend to production
        run: |
          echo "Deploying Go backend to production environment"
          # Add your Go backend production deployment commands here
