name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml exec backend-go go test
          docker-compose -f docker-compose.yml exec backend-python pytest
          docker-compose -f docker-compose.yml exec frontend-react npm test
